USE sql10731376;

drop table sql10731376.StudentResponses ;
CREATE TABLE sql10731376.StudentResponses (
    StudentID INT,
    StudentCountry VARCHAR(100),
    QuestionID INT,
    TypeOfAnswer VARCHAR(50),
    QuestionLevel VARCHAR(50),
    Topic VARCHAR(100),
    Subtopic VARCHAR(100),
    Keywords TEXT
);


INSERT INTO sql10731376.StudentResponses (StudentID, StudentCountry, QuestionID, TypeOfAnswer, QuestionLevel, Topic, Subtopic, Keywords)
VALUES
(1, 'España', 101, 'Correct', 'Intermedio', 'Álgebra', 'Ecuaciones Lineales', 'ecuaciones, lineales, álgebra'),
(2, 'México', 102, 'Incorrect', 'Avanzado', 'Geometría', 'Áreas de Figuras', 'geometría, áreas, figuras'),
(3, 'Colombia', 103, 'Correct', 'Básico', 'Cálculo', 'Derivadas', 'cálculo, derivadas'),
(4, 'Argentina', 104, 'Correct', 'Intermedio', 'Estadística', 'Regresión Lineal', 'estadística, regresión, lineal'),
(5, 'Chile', 105, 'Incorrect', 'Avanzado', 'Álgebra', 'Matrices', 'álgebra, matrices'),
(6, 'Perú', 106, 'Correct', 'Básico', 'Trigonometría', 'Funciones Trigonométricas', 'trigonometría, funciones, trigonométricas'),
(7, 'Venezuela', 107, 'Correct', 'Intermedio', 'Probabilidad', 'Distribuciones', 'probabilidad, distribuciones'),
(8, 'Ecuador', 108, 'Incorrect', 'Básico', 'Álgebra', 'Sistemas de Ecuaciones', 'álgebra, sistemas, ecuaciones'),
(9, 'Bolivia', 109, 'Correct', 'Avanzado', 'Estadística', 'Análisis de Varianza', 'estadística, análisis, varianza'),
(10, 'Paraguay', 110, 'Incorrect', 'Intermedio', 'Álgebra', 'Polinomios', 'álgebra, polinomios'),
(11, 'Uruguay', 111, 'Correct', 'Básico', 'Geometría', 'Círculos', 'geometría, círculos'),
(12, 'Brasil', 112, 'Incorrect', 'Avanzado', 'Cálculo', 'Integrales', 'cálculo, integrales'),
(13, 'Chile', 113, 'Correct', 'Intermedio', 'Trigonometría', 'Identidades Trigonométricas', 'trigonometría, identidades'),
(14, 'Colombia', 114, 'Incorrect', 'Básico', 'Álgebra', 'Funciones', 'álgebra, funciones'),
(15, 'México', 115, 'Correct', 'Avanzado', 'Álgebra', 'Teoremas de Álgebra', 'álgebra, teoremas'),
(16, 'Perú', 116, 'Incorrect', 'Intermedio', 'Estadística', 'Medidas de Tendencia Central', 'estadística, medidas, tendencia, central'),
(17, 'Argentina', 117, 'Correct', 'Básico', 'Cálculo', 'Límites', 'cálculo, límites'),
(18, 'Venezuela', 118, 'Incorrect', 'Avanzado', 'Probabilidad', 'Teorema de Bayes', 'probabilidad, teorema, bayes'),
(19, 'Ecuador', 119, 'Correct', 'Intermedio', 'Geometría', 'Transformaciones', 'geometría, transformaciones'),
(20, 'Bolivia', 120, 'Incorrect', 'Básico', 'Álgebra', 'Ecuaciones Cuadráticas', 'álgebra, ecuaciones, cuadráticas'),
(21, 'Colombia', 121, 'Correct', 'Avanzado', 'Álgebra', 'Espacios Vectoriales', 'álgebra, espacios, vectoriales'),
(22, 'Chile', 122, 'Incorrect', 'Intermedio', 'Estadística', 'Correlación', 'estadística, correlación'),
(23, 'México', 123, 'Correct', 'Básico', 'Trigonometría', 'Ángulos', 'trigonometría, ángulos'),
(24, 'Perú', 124, 'Incorrect', 'Avanzado', 'Cálculo', 'Teoremas Fundamentales', 'cálculo, teoremas, fundamentales'),
(25, 'Argentina', 125, 'Correct', 'Intermedio', 'Álgebra', 'Funciones Exponenciales', 'álgebra, funciones, exponenciales'),
(26, 'Venezuela', 126, 'Incorrect', 'Básico', 'Geometría', 'Polígonos', 'geometría, polígonos'),
(27, 'Ecuador', 127, 'Correct', 'Avanzado', 'Probabilidad', 'Inferencia Estadística', 'probabilidad, inferencia, estadística'),
(28, 'Bolivia', 128, 'Incorrect', 'Intermedio', 'Trigonometría', 'Leyes Trigonométricas', 'trigonometría, leyes'),
(29, 'Uruguay', 129, 'Correct', 'Básico', 'Álgebra', 'Ecuaciones Simples', 'álgebra, ecuaciones, simples'),
(30, 'Brasil', 130, 'Incorrect', 'Avanzado', 'Estadística', 'Regresión No Lineal', 'estadística, regresión, no lineal'),
(31, 'Chile', 131, 'Correct', 'Intermedio', 'Cálculo', 'Series de Taylor', 'cálculo, series, taylor'),
(32, 'Colombia', 132, 'Incorrect', 'Básico', 'Geometría', 'Volumenes', 'geometría, volúmenes'),
(33, 'México', 133, 'Correct', 'Avanzado', 'Álgebra', 'Polinomios de Segundo Grado', 'álgebra, polinomios, segundo grado'),
(34, 'Perú', 134, 'Incorrect', 'Intermedio', 'Trigonometría', 'Sine y Coseno', 'trigonometría, sine, coseno'),
(35, 'Argentina', 135, 'Correct', 'Básico', 'Estadística', 'Desviación Estándar', 'estadística, desviación, estándar'),
(36, 'Venezuela', 136, 'Incorrect', 'Avanzado', 'Cálculo', 'Cálculo Multivariable', 'cálculo, multivariable'),
(37, 'Ecuador', 137, 'Correct', 'Intermedio', 'Álgebra', 'Ecuaciones Diferenciales', 'álgebra, ecuaciones, diferenciales'),
(38, 'Bolivia', 138, 'Incorrect', 'Básico', 'Probabilidad', 'Eventos Independientes', 'probabilidad, eventos, independientes'),
(39, 'Uruguay', 139, 'Correct', 'Avanzado', 'Geometría', 'Teorema de Pitágoras', 'geometría, pitágoras'),
(40, 'Brasil', 140, 'Incorrect', 'Intermedio', 'Trigonometría', 'Funciones de Ángulo Agudo', 'trigonometría, ángulo, agudo'),
(41, 'Chile', 141, 'Correct', 'Básico', 'Estadística', 'Histograma', 'estadística, histograma'),
(42, 'Colombia', 142, 'Incorrect', 'Avanzado', 'Álgebra', 'Teoría de Grupos', 'álgebra, teoría, grupos'),
(43, 'México', 143, 'Correct', 'Intermedio', 'Cálculo', 'Derivadas Parciales', 'cálculo, derivadas, parciales'),
(44, 'Perú', 144, 'Incorrect', 'Básico', 'Álgebra', 'Suma y Resta', 'álgebra, suma, resta'),
(45, 'Argentina', 145, 'Correct', 'Avanzado', 'Probabilidad', 'Distribuciones de Probabilidad', 'probabilidad, distribuciones'),
(46, 'Venezuela', 146, 'Incorrect', 'Intermedio', 'Geometría', 'Áreas de Figuras Irregulares', 'geometría, áreas, figuras, irregulares'),
(47, 'Ecuador', 147, 'Correct', 'Básico', 'Trigonometría', 'Ley de los Senos', 'trigonometría, ley, senos'),
(48, 'Bolivia', 148, 'Incorrect', 'Avanzado', 'Cálculo', 'Ecuaciones Diferenciales Ordinarias', 'cálculo, ecuaciones, diferenciales, ordinarias'),
(49, 'Uruguay', 149, 'Correct', 'Intermedio', 'Álgebra', 'Ecuaciones de Segundo Grado', 'álgebra, ecuaciones, segundo grado'),
(50, 'Brasil', 150, 'Incorrect', 'Básico', 'Estadística', 'Moda y Mediana', 'estadística, moda, mediana'),
(51, 'Paraguay', 151, 'Correct', 'Intermedio', 'Cálculo', 'Series de Fourier', 'cálculo, series, fourier'),
(52, 'Uruguay', 152, 'Incorrect', 'Básico', 'Álgebra', 'Operaciones Básicas', 'álgebra, operaciones, básicas'),
(53, 'Brasil', 153, 'Correct', 'Avanzado', 'Geometría', 'Teorema de Euler', 'geometría, teorema, euler'),
(54, 'Chile', 154, 'Incorrect', 'Intermedio', 'Álgebra', 'Factorización', 'álgebra, factorización'),
(55, 'Colombia', 155, 'Correct', 'Básico', 'Trigonometría', 'Ángulos Agudos', 'trigonometría, ángulos, agudos'),
(56, 'México', 156, 'Incorrect', 'Avanzado', 'Cálculo', 'Integrales Impropias', 'cálculo, integrales, impropias'),
(57, 'Perú', 157, 'Correct', 'Intermedio', 'Estadística', 'Pruebas de Hipótesis', 'estadística, pruebas, hipótesis'),
(58, 'Argentina', 158, 'Incorrect', 'Básico', 'Álgebra', 'Ecuaciones Simples', 'álgebra, ecuaciones, simples'),
(59, 'Venezuela', 159, 'Correct', 'Avanzado', 'Probabilidad', 'Teoremas de Probabilidad', 'probabilidad, teoremas'),
(60, 'Ecuador', 160, 'Incorrect', 'Intermedio', 'Geometría', 'Cónicas', 'geometría, cónicas'),
(61, 'Bolivia', 161, 'Correct', 'Básico', 'Álgebra', 'Sumas y Restas', 'álgebra, sumas, restas'),
(62, 'Uruguay', 162, 'Incorrect', 'Avanzado', 'Cálculo', 'Series de Taylor', 'cálculo, series, taylor'),
(63, 'Brasil', 163, 'Correct', 'Intermedio', 'Trigonometría', 'Leyes de Trigonometría', 'trigonometría, leyes'),
(64, 'Chile', 164, 'Incorrect', 'Básico', 'Estadística', 'Promedio', 'estadística, promedio'),
(65, 'Colombia', 165, 'Correct', 'Avanzado', 'Álgebra', 'Teoremas de Álgebra Abstracta', 'álgebra, teoremas, abstracta'),
(66, 'México', 166, 'Incorrect', 'Intermedio', 'Cálculo', 'Derivadas de Funciones', 'cálculo, derivadas, funciones'),
(67, 'Perú', 167, 'Correct', 'Básico', 'Álgebra', 'Ecuaciones Lineales Simples', 'álgebra, ecuaciones, lineales'),
(68, 'Argentina', 168, 'Incorrect', 'Avanzado', 'Estadística', 'Análisis de Regresión', 'estadística, análisis, regresión'),
(69, 'Venezuela', 169, 'Correct', 'Intermedio', 'Cálculo', 'Límites y Continuidad', 'cálculo, límites, continuidad'),
(70, 'Ecuador', 170, 'Incorrect', 'Básico', 'Trigonometría', 'Ángulos de Triángulos', 'trigonometría, ángulos, triángulos'),
(71, 'Bolivia', 171, 'Correct', 'Avanzado', 'Álgebra', 'Teoría de Anillos', 'álgebra, teoría, anillos'),
(72, 'Uruguay', 172, 'Incorrect', 'Intermedio', 'Estadística', 'Pruebas de Significancia', 'estadística, pruebas, significancia'),
(73, 'Brasil', 173, 'Correct', 'Básico', 'Geometría', 'Figuras Geométricas', 'geometría, figuras'),
(74, 'Chile', 174, 'Incorrect', 'Avanzado', 'Probabilidad', 'Distribuciones Continuas', 'probabilidad, distribuciones, continuas'),
(75, 'Colombia', 175, 'Correct', 'Intermedio', 'Álgebra', 'Matrices y Determinantes', 'álgebra, matrices, determinantes'),
(76, 'México', 176, 'Incorrect', 'Básico', 'Cálculo', 'Función Exponencial', 'cálculo, función, exponencial'),
(77, 'Perú', 177, 'Correct', 'Avanzado', 'Trigonometría', 'Identidades Trigonométricas Avanzadas', 'trigonometría, identidades, avanzadas'),
(78, 'Argentina', 178, 'Incorrect', 'Intermedio', 'Estadística', 'Análisis Descriptivo', 'estadística, análisis, descriptivo'),
(79, 'Venezuela', 179, 'Correct', 'Básico', 'Álgebra', 'Operaciones con Polinomios', 'álgebra, operaciones, polinomios'),
(80, 'Ecuador', 180, 'Incorrect', 'Avanzado', 'Geometría', 'Espacios Métricos', 'geometría, espacios, métricos'),
(81, 'Bolivia', 181, 'Correct', 'Intermedio', 'Cálculo', 'Teorema Fundamental del Cálculo', 'cálculo, teorema, fundamental'),
(82, 'Uruguay', 182, 'Incorrect', 'Básico', 'Álgebra', 'Ecuaciones Simples', 'álgebra, ecuaciones, simples'),
(83, 'Brasil', 183, 'Correct', 'Avanzado', 'Estadística', 'Métodos de Inferencia', 'estadística, métodos, inferencia'),
(84, 'Chile', 184, 'Incorrect', 'Intermedio', 'Álgebra', 'Sistemas de Ecuaciones Lineales', 'álgebra, sistemas, ecuaciones'),
(85, 'Colombia', 185, 'Correct', 'Básico', 'Trigonometría', 'Relaciones Trigonométricas', 'trigonometría, relaciones'),
(86, 'México', 186, 'Incorrect', 'Avanzado', 'Cálculo', 'Ecuaciones Diferenciales Parciales', 'cálculo, ecuaciones, diferenciales'),
(87, 'Perú', 187, 'Correct', 'Intermedio', 'Geometría', 'Áreas de Figuras Planas', 'geometría, áreas, figuras'),
(88, 'Argentina', 188, 'Incorrect', 'Básico', 'Estadística', 'Distribución Normal', 'estadística, distribución, normal'),
(89, 'Venezuela', 189, 'Correct', 'Avanzado', 'Álgebra', 'Espacios Vectoriales', 'álgebra, espacios, vectoriales'),
(90, 'Ecuador', 190, 'Incorrect', 'Intermedio', 'Trigonometría', 'Ley de los Cosenos', 'trigonometría, ley, cosenos'),
(91, 'Bolivia', 191, 'Correct', 'Básico', 'Álgebra', 'Ecuaciones Lineales con Dos Variables', 'álgebra, ecuaciones, dos variables'),
(92, 'Uruguay', 192, 'Incorrect', 'Avanzado', 'Cálculo', 'Series de Potencias', 'cálculo, series, potencias'),
(93, 'Brasil', 193, 'Correct', 'Intermedio', 'Estadística', 'Intervalos de Confianza', 'estadística, intervalos, confianza'),
(94, 'Chile', 194, 'Incorrect', 'Básico', 'Geometría', 'Líneas y Ángulos', 'geometría, líneas, ángulos'),
(95, 'Colombia', 195, 'Correct', 'Avanzado', 'Probabilidad', 'Variables Aleatorias', 'probabilidad, variables, aleatorias'),
(96, 'México', 196, 'Incorrect', 'Intermedio', 'Álgebra', 'Ecuaciones de Primer Grado', 'álgebra, ecuaciones, primer grado'),
(97, 'Perú', 197, 'Correct', 'Básico', 'Trigonometría', 'Funciones Trigonométricas Básicas', 'trigonometría, funciones, básicas'),
(98, 'Argentina', 198, 'Incorrect', 'Avanzado', 'Estadística', 'Métodos Bayesianos', 'estadística, bayesianos'),
(99, 'Venezuela', 199, 'Correct', 'Intermedio', 'Cálculo', 'Cálculo Diferencial', 'cálculo, diferencial'),
(100, 'Ecuador', 200, 'Incorrect', 'Básico', 'Álgebra', 'Polinomios Básicos', 'álgebra, polinomios'),
(101, 'Uruguay', 201, 'Incorrect', 'Intermedio', 'Álgebra', 'Ecuaciones No Lineales', 'álgebra, ecuaciones, no lineales'),
(102, 'Brasil', 202, 'Correct', 'Básico', 'Geometría', 'Figuras Planas', 'geometría, figuras, planas'),
(103, 'Chile', 203, 'Incorrect', 'Avanzado', 'Cálculo', 'Cálculo en Varias Variables', 'cálculo, varias, variables'),
(104, 'Colombia', 204, 'Correct', 'Intermedio', 'Estadística', 'Pruebas de Normalidad', 'estadística, pruebas, normalidad'),
(105, 'México', 205, 'Incorrect', 'Básico', 'Trigonometría', 'Ángulos y Círculos', 'trigonometría, ángulos, círculos'),
(106, 'Perú', 206, 'Correct', 'Avanzado', 'Álgebra', 'Estructuras Algebraicas', 'álgebra, estructuras, algebraicas'),
(107, 'Argentina', 207, 'Incorrect', 'Intermedio', 'Geometría', 'Sólidos Geométricos', 'geometría, sólidos'),
(108, 'Venezuela', 208, 'Correct', 'Básico', 'Estadística', 'Histogramas Básicos', 'estadística, histogramas'),
(109, 'Ecuador', 209, 'Incorrect', 'Avanzado', 'Cálculo', 'Teoría de Integrales', 'cálculo, teoría, integrales'),
(110, 'Bolivia', 210, 'Correct', 'Intermedio', 'Álgebra', 'Álgebra Abstracta', 'álgebra, abstracta'),
(111, 'Uruguay', 211, 'Incorrect', 'Básico', 'Geometría', 'Punto y Línea', 'geometría, punto, línea'),
(112, 'Brasil', 212, 'Correct', 'Avanzado', 'Trigonometría', 'Identidades Avanzadas', 'trigonometría, identidades, avanzadas'),
(113, 'Chile', 213, 'Incorrect', 'Intermedio', 'Estadística', 'Modelos Estadísticos', 'estadística, modelos'),
(114, 'Colombia', 214, 'Correct', 'Básico', 'Cálculo', 'Derivadas Simples', 'cálculo, derivadas'),
(115, 'México', 215, 'Incorrect', 'Avanzado', 'Álgebra', 'Álgebra Computacional', 'álgebra, computacional'),
(116, 'Perú', 216, 'Correct', 'Intermedio', 'Geometría', 'Transformaciones Geométricas', 'geometría, transformaciones'),
(117, 'Argentina', 217, 'Incorrect', 'Básico', 'Estadística', 'Medidas de Dispersión', 'estadística, dispersión'),
(118, 'Venezuela', 218, 'Correct', 'Avanzado', 'Álgebra', 'Teoría de Códigos', 'álgebra, teoría, códigos'),
(119, 'Ecuador', 219, 'Incorrect', 'Intermedio', 'Cálculo', 'Ecuaciones Diferenciales', 'cálculo, ecuaciones, diferenciales'),
(120, 'Bolivia', 220, 'Correct', 'Básico', 'Trigonometría', 'Ley de los Senos', 'trigonometría, ley, senos'),
(121, 'Uruguay', 221, 'Incorrect', 'Avanzado', 'Geometría', 'Espacios Euclidianos', 'geometría, espacios, euclidianos'),
(122, 'Brasil', 222, 'Correct', 'Intermedio', 'Estadística', 'Estimación de Parámetros', 'estadística, estimación'),
(123, 'Chile', 223, 'Incorrect', 'Básico', 'Álgebra', 'Operaciones con Fracciones', 'álgebra, fracciones'),
(124, 'Colombia', 224, 'Correct', 'Avanzado', 'Cálculo', 'Series de Fourier', 'cálculo, series, fourier'),
(125, 'México', 225, 'Incorrect', 'Intermedio', 'Trigonometría', 'Ángulos Obtusos', 'trigonometría, ángulos, obtusos'),
(126, 'Perú', 226, 'Correct', 'Básico', 'Álgebra', 'Ecuaciones de Primer Grado', 'álgebra, ecuaciones'),
(127, 'Argentina', 227, 'Incorrect', 'Avanzado', 'Geometría', 'Teoremas de Geometría Analítica', 'geometría, teoremas, analítica'),
(128, 'Venezuela', 228, 'Correct', 'Intermedio', 'Estadística', 'Regresión Lineal', 'estadística, regresión'),
(129, 'Ecuador', 229, 'Incorrect', 'Básico', 'Cálculo', 'Límites de Funciones', 'cálculo, límites'),
(130, 'Bolivia', 230, 'Correct', 'Avanzado', 'Álgebra', 'Espacios Normados', 'álgebra, espacios, normados'),
(131, 'Uruguay', 231, 'Incorrect', 'Intermedio', 'Geometría', 'Propiedades de los Triángulos', 'geometría, triángulos'),
(132, 'Brasil', 232, 'Correct', 'Básico', 'Estadística', 'Medidas de Tendencia Central', 'estadística, medidas'),
(133, 'Chile', 233, 'Incorrect', 'Avanzado', 'Álgebra', 'Teoría de Anillos', 'álgebra, teoría, anillos'),
(134, 'Colombia', 234, 'Correct', 'Intermedio', 'Cálculo', 'Integrales Definidas', 'cálculo, integrales'),
(135, 'México', 235, 'Incorrect', 'Básico', 'Trigonometría', 'Ángulos en Triángulos', 'trigonometría, triángulos'),
(136, 'Perú', 236, 'Correct', 'Avanzado', 'Geometría', 'Geometría Analítica', 'geometría, analítica'),
(137, 'Argentina', 237, 'Incorrect', 'Intermedio', 'Estadística', 'Histograma de Frecuencias', 'estadística, histograma'),
(138, 'Venezuela', 238, 'Correct', 'Básico', 'Álgebra', 'Suma de Polinomios', 'álgebra, suma, polinomios'),
(139, 'Ecuador', 239, 'Incorrect', 'Avanzado', 'Cálculo', 'Teorema Fundamental', 'cálculo, teorema, fundamental'),
(140, 'Bolivia', 240, 'Correct', 'Intermedio', 'Trigonometría', 'Funciones Trigonométricas', 'trigonometría, funciones'),
(141, 'Uruguay', 241, 'Incorrect', 'Básico', 'Geometría', 'Área de Triángulos', 'geometría, triángulos'),
(142, 'Brasil', 242, 'Correct', 'Avanzado', 'Estadística', 'Pruebas de Hipótesis Avanzadas', 'estadística, pruebas, hipótesis'),
(143, 'Chile', 243, 'Incorrect', 'Intermedio', 'Álgebra', 'Matrices Inversas', 'álgebra, matrices, inversas'),
(144, 'Colombia', 244, 'Correct', 'Básico', 'Cálculo', 'Derivadas de Funciones', 'cálculo, derivadas'),
(145, 'México', 245, 'Incorrect', 'Avanzado', 'Trigonometría', 'Ecuaciones Trigonométricas', 'trigonometría, ecuaciones'),
(146, 'Perú', 246, 'Correct', 'Intermedio', 'Álgebra', 'Sistema de Ecuaciones', 'álgebra, sistemas'),
(147, 'Argentina', 247, 'Incorrect', 'Básico', 'Estadística', 'Medidas de Dispersión', 'estadística, dispersión'),
(148, 'Venezuela', 248, 'Correct', 'Avanzado', 'Álgebra', 'Teoría de Números', 'álgebra, teoría, números'),
(149, 'Ecuador', 249, 'Incorrect', 'Intermedio', 'Geometría', 'Área de Figuras Complejas', 'geometría, figuras, complejas'),
(150, 'Bolivia', 250, 'Correct', 'Básico', 'Trigonometría', 'Ángulos en Círculos', 'trigonometría, ángulos, círculos'),
(151, 'Uruguay', 251, 'Incorrect', 'Avanzado', 'Estadística', 'Inferencia Estadística Avanzada', 'estadística, inferencia'),
(152, 'Brasil', 252, 'Correct', 'Intermedio', 'Cálculo', 'Series de Taylor', 'cálculo, series, taylor'),
(153, 'Chile', 253, 'Incorrect', 'Básico', 'Álgebra', 'Operaciones con Números Reales', 'álgebra, números, reales'),
(154, 'Colombia', 254, 'Correct', 'Avanzado', 'Geometría', 'Geometría Proyectiva', 'geometría, proyectiva'),
(155, 'México', 255, 'Incorrect', 'Intermedio', 'Trigonometría', 'Ángulos Agudos y Obtusos', 'trigonometría, ángulos'),
(156, 'Perú', 256, 'Correct', 'Básico', 'Álgebra', 'Operaciones con Polinomios', 'álgebra, operaciones, polinomios'),
(157, 'Argentina', 257, 'Incorrect', 'Avanzado', 'Estadística', 'Métodos de Ajuste de Curvas', 'estadística, ajuste'),
(158, 'Venezuela', 258, 'Correct', 'Intermedio', 'Álgebra', 'Ecuaciones Diferenciales Ordinarias', 'álgebra, ecuaciones'),
(159, 'Ecuador', 259, 'Incorrect', 'Básico', 'Cálculo', 'Conceptos Fundamentales de Cálculo', 'cálculo, conceptos'),
(160, 'Bolivia', 260, 'Correct', 'Avanzado', 'Trigonometría', 'Funciones Trigonométricas Avanzadas', 'trigonometría, funciones'),
(161, 'Uruguay', 261, 'Incorrect', 'Intermedio', 'Geometría', 'Volúmenes de Sólidos', 'geometría, volúmenes'),
(162, 'Brasil', 262, 'Correct', 'Básico', 'Estadística', 'Medidas de Tendencia Central', 'estadística, medidas'),
(163, 'Chile', 263, 'Incorrect', 'Avanzado', 'Álgebra', 'Teoría de Anillos', 'álgebra, teoría'),
(164, 'Colombia', 264, 'Correct', 'Intermedio', 'Cálculo', 'Cálculo de Áreas', 'cálculo, áreas'),
(165, 'México', 265, 'Incorrect', 'Básico', 'Trigonometría', 'Identidades Trigonométricas Básicas', 'trigonometría, identidades'),
(166, 'Perú', 266, 'Correct', 'Avanzado', 'Geometría', 'Geometría de Espacios Métricos', 'geometría, espacios'),
(167, 'Argentina', 267, 'Incorrect', 'Intermedio', 'Estadística', 'Regresión Lineal Simple', 'estadística, regresión'),
(168, 'Venezuela', 268, 'Correct', 'Básico', 'Álgebra', 'Suma y Resta de Polinomios', 'álgebra, suma, resta'),
(169, 'Ecuador', 269, 'Incorrect', 'Avanzado', 'Cálculo', 'Integración Avanzada', 'cálculo, integración'),
(170, 'Bolivia', 270, 'Correct', 'Intermedio', 'Trigonometría', 'Ley de los Cosenos', 'trigonometría, ley'),
(171, 'Uruguay', 271, 'Incorrect', 'Básico', 'Geometría', 'Propiedades de Círculos', 'geometría, círculos'),
(172, 'Brasil', 272, 'Correct', 'Avanzado', 'Estadística', 'Métodos de Estimación', 'estadística, estimación'),
(173, 'Chile', 273, 'Incorrect', 'Intermedio', 'Álgebra', 'Matrices y Determinantes', 'álgebra, matrices'),
(174, 'Colombia', 274, 'Correct', 'Básico', 'Cálculo', 'Derivadas de Polinomios', 'cálculo, derivadas'),
(175, 'México', 275, 'Incorrect', 'Avanzado', 'Trigonometría', 'Ecuaciones Trigonométricas Avanzadas', 'trigonometría, ecuaciones'),
(176, 'Perú', 276, 'Correct', 'Intermedio', 'Álgebra', 'Sistemas de Ecuaciones', 'álgebra, sistemas'),
(177, 'Argentina', 277, 'Incorrect', 'Básico', 'Estadística', 'Distribución Normal', 'estadística, distribución'),
(178, 'Venezuela', 278, 'Correct', 'Avanzado', 'Álgebra', 'Álgebra Lineal Avanzada', 'álgebra, lineal'),
(179, 'Ecuador', 279, 'Incorrect', 'Intermedio', 'Geometría', 'Propiedades de los Polígonos', 'geometría, polígonos'),
(180, 'Bolivia', 280, 'Correct', 'Básico', 'Trigonometría', 'Funciones Trigonométricas', 'trigonometría, funciones'),
(181, 'Uruguay', 281, 'Incorrect', 'Avanzado', 'Estadística', 'Métodos de Inferencia Estadística', 'estadística, inferencia'),
(182, 'Brasil', 282, 'Correct', 'Intermedio', 'Cálculo', 'Ecuaciones Diferenciales Simples', 'cálculo, ecuaciones'),
(183, 'Chile', 283, 'Incorrect', 'Básico', 'Álgebra', 'Operaciones Básicas', 'álgebra, operaciones'),
(184, 'Colombia', 284, 'Correct', 'Avanzado', 'Geometría', 'Geometría Algebraica', 'geometría, algebraica'),
(185, 'México', 285, 'Incorrect', 'Intermedio', 'Trigonometría', 'Identidades Trigonométricas', 'trigonometría, identidades'),
(186, 'Perú', 286, 'Correct', 'Básico', 'Álgebra', 'Ecuaciones Simples', 'álgebra, ecuaciones'),
(187, 'Argentina', 287, 'Incorrect', 'Avanzado', 'Estadística', 'Análisis Multivariante', 'estadística, multivariante'),
(188, 'Venezuela', 288, 'Correct', 'Intermedio', 'Álgebra', 'Matrices y Operaciones', 'álgebra, matrices'),
(189, 'Ecuador', 289, 'Incorrect', 'Básico', 'Cálculo', 'Conceptos Básicos', 'cálculo, conceptos'),
(190, 'Bolivia', 290, 'Correct', 'Avanzado', 'Trigonometría', 'Identidades Trigonométricas Avanzadas', 'trigonometría, identidades'),
(191, 'Uruguay', 291, 'Incorrect', 'Intermedio', 'Geometría', 'Áreas de Polígonos', 'geometría, áreas'),
(192, 'Brasil', 292, 'Correct', 'Básico', 'Estadística', 'Medidas de Tendencia Central', 'estadística, medidas'),
(193, 'Chile', 293, 'Incorrect', 'Avanzado', 'Álgebra', 'Teoría de Números', 'álgebra, teoría'),
(194, 'Colombia', 294, 'Correct', 'Intermedio', 'Cálculo', 'Integrales Definidas', 'cálculo, integrales'),
(195, 'México', 295, 'Incorrect', 'Básico', 'Trigonometría', 'Funciones Trigonométricas', 'trigonometría, funciones'),
(196, 'Perú', 296, 'Correct', 'Avanzado', 'Geometría', 'Geometría Proyectiva', 'geometría, proyectiva'),
(197, 'Argentina', 297, 'Incorrect', 'Intermedio', 'Estadística', 'Regresión Lineal Múltiple', 'estadística, regresión'),
(198, 'Venezuela', 298, 'Correct', 'Básico', 'Álgebra', 'Polinomios Básicos', 'álgebra, polinomios'),
(199, 'Ecuador', 299, 'Incorrect', 'Avanzado', 'Cálculo', 'Teorema Fundamental del Cálculo', 'cálculo, teorema'),
(200, 'Bolivia', 300, 'Correct', 'Intermedio', 'Trigonometría', 'Ley de los Cosenos', 'trigonometría, ley');

select * FROM sql10731376.StudentResponses;


-- ¿Cómo varía el desempeño de los estudiantes en diferentes niveles de dificultad y temas matemáticos según su país de origen, y qué factores están asociados con los aciertos o errores en sus respuestas?

-- Consulta 1: Desempeño por País
SELECT StudentCountry, 
       AVG(CASE WHEN TypeOfAnswer = 'Correct' THEN 1 ELSE 0 END) AS CorrectAnswerRate
FROM sql10731376.StudentResponses
GROUP BY StudentCountry;

-- Consulta 2: Desempeño por Nivel de Dificultad
SELECT QuestionLevel, 
       AVG(CASE WHEN TypeOfAnswer = 'Correct' THEN 1 ELSE 0 END) AS CorrectAnswerRate
FROM sql10731376.StudentResponses
GROUP BY QuestionLevel;

-- Consulta 3: Desempeño por Tema y Subtema
SELECT Topic, 
       Subtopic, 
       AVG(CASE WHEN TypeOfAnswer = 'Correct' THEN 1 ELSE 0 END) AS CorrectAnswerRate
FROM sql10731376.StudentResponses
GROUP BY Topic, Subtopic;

-- Consulta 4: Desempeño por País y Nivel de Dificultad
SELECT StudentCountry, 
       QuestionLevel, 
       AVG(CASE WHEN TypeOfAnswer = 'Correct' THEN 1 ELSE 0 END) AS CorrectAnswerRate
FROM sql10731376.StudentResponses
GROUP BY StudentCountry, QuestionLevel;

-- Consulta 5: Desempeño por País y Tema
SELECT StudentCountry, 
       Topic, 
       AVG(CASE WHEN TypeOfAnswer = 'Correct' THEN 1 ELSE 0 END) AS CorrectAnswerRate
FROM sql10731376.StudentResponses
GROUP BY StudentCountry, Topic;



